=== afuentesan/xmltui/xmltui-lib/examples/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!-- ========================================== -->
    <!-- TIPOS PERSONALIZADOS Y RESTRICCIONES       -->
    <!-- ========================================== -->
    
    <xs:simpleType name="ratioType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d+,\s*\d+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="alignType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="left"/>
            <xs:enumeration value="right"/>
            <xs:enumeration value="center"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="dirType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="horizontal"/>
            <xs:enumeration value="vertical"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="outputType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="str"/>
            <xs:enumeration value="strvec"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Atributos que comparten TODOS los nodos dentro de body -->
    <xs:attributeGroup name="commonBodyAttributes">
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="class" type="xs:string"/>
        <xs:attribute name="fill" type="xs:unsignedInt"/>
        <xs:attribute name="percentage" type="xs:unsignedInt"/>
        <xs:attribute name="min" type="xs:unsignedInt"/>
        <xs:attribute name="max" type="xs:unsignedInt"/>
        <xs:attribute name="length" type="xs:unsignedInt"/>
        <xs:attribute name="ratio" type="ratioType"/>
        <!-- Nuevos atributos de refresco como enteros sin signo -->
        <xs:attribute name="refresh-sec" type="xs:unsignedInt"/>
        <xs:attribute name="refresh-ms" type="xs:unsignedInt"/>
        <!-- Permite los atributos extra como data-* -->
        <xs:anyAttribute namespace="##any" processContents="skip"/>
    </xs:attributeGroup>

    <!-- Todos los elementos posibles que pueden anidarse dentro de body, layout y template -->
    <xs:group name="bodyElements">
        <xs:choice>
            <xs:element ref="layout"/>
            <xs:element ref="line"/>
            <xs:element ref="span"/>
            <xs:element ref="input"/>
            <xs:element ref="a"/>
            <xs:element ref="button"/>
            <xs:element ref="command"/>
        </xs:choice>
    </xs:group>

    <!-- ========================================== -->
    <!-- ELEMENTOS DEL BODY                         -->
    <!-- ========================================== -->
    <xs:element name="layout">
        <xs:complexType>
            <xs:group ref="bodyElements" minOccurs="0" maxOccurs="unbounded"/>
            <xs:attribute name="dir" type="dirType"/>
            <xs:attributeGroup ref="commonBodyAttributes"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="line">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="span" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="align" type="alignType"/>
            <xs:attributeGroup ref="commonBodyAttributes"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="span">
        <xs:complexType mixed="true">
            <xs:attributeGroup ref="commonBodyAttributes"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="input">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="value" type="xs:string"/>
            <xs:attribute name="align" type="alignType"/>
            <xs:attributeGroup ref="commonBodyAttributes"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="a">
        <xs:complexType mixed="true">
            <xs:attribute name="src" type="xs:string"/>
            <xs:attribute name="align" type="alignType"/>
            <xs:attributeGroup ref="commonBodyAttributes"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="button">
        <xs:complexType mixed="true">
            <xs:attribute name="enter" type="xs:string"/>
            <xs:attribute name="align" type="alignType"/>
            <xs:attribute name="enter-replace-childs" type="xs:string"/>
            <xs:attribute name="enter-replace-node" type="xs:string"/>
            <xs:attribute name="enter-change-value" type="xs:string"/>
            <xs:attribute name="enter-data" type="xs:string"/>
            <xs:attributeGroup ref="commonBodyAttributes"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="template">
        <xs:complexType>
            <xs:group ref="bodyElements" minOccurs="0" maxOccurs="unbounded"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="command">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="template" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="exec" type="xs:string"/>
            <xs:attribute name="child-type" type="xs:string"/>
            <xs:attribute name="child-align" type="alignType"/>
            <xs:attribute name="child-dir" type="dirType"/>
            <xs:attribute name="output" type="outputType"/>
            <xs:attributeGroup ref="commonBodyAttributes"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="body">
        <xs:complexType>
            <xs:group ref="bodyElements" minOccurs="0" maxOccurs="unbounded"/>
            <xs:attribute name="dir" type="dirType"/>
            <xs:attributeGroup ref="commonBodyAttributes"/>
        </xs:complexType>
    </xs:element>

    <!-- ========================================== -->
    <!-- ELEMENTOS DEL HEAD                         -->
    <!-- ========================================== -->
    <xs:element name="style">
        <xs:complexType mixed="true">
            <xs:attribute name="src" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="env">
        <xs:complexType mixed="true">
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="env-data">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="arg" type="xs:string"/>

    <xs:element name="arg-data">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="envs">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="env"/>
                <xs:element ref="env-data"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name="args">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="arg"/>
                <xs:element ref="arg-data"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name="code">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:element ref="envs" minOccurs="0"/>
                <xs:element ref="args" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="command" type="xs:string"/>
            <xs:attribute name="src" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="head">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="style"/>
                <xs:element ref="code"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <!-- ========================================== -->
    <!-- ELEMENTO RAÍZ                              -->
    <!-- ========================================== -->
    <xs:element name="rtml">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="head" minOccurs="0"/>
                <xs:element ref="body"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== afuentesan/xmltui/examples/cpuinfo/index.xml
<rtml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/afuentesan/xmltui/refs/heads/main/schema.xsd"
>
    <head>
        <code command="/usr/bin/node" name="parse-info">
            <args>
                <arg>-e</arg>
                <arg>
                    <![CDATA[ 

                        function cpus_map( input )
                        {
                            let map = {};

                            input.split( "\n" )
                            .filter( ( s ) => s.trim() != "" )
                            .forEach(
                                ( s ) => {
                                    let res = key_numbers( s );

                                    map[ res.key ] = res;
                                }
                            );

                            return map;
                        }

                        function key_numbers( input )
                        {
                            let cols = input.split( " " ).filter( ( s ) => s.trim() != "" ).map( ( s ) => s.trim() );

                            return {
                                key : cols[ 0 ],
                                numbers : numbers_from_cols( cols )
                            }
                        }

                        function numbers_from_cols( cols )
                        {
                            let idle = Number( cols[ 4 ] ) + Number( cols[ 5 ] );
                            let non_idle = Number( cols[ 1 ] ) + Number( cols[ 2 ] ) + Number( cols[ 3 ] ) +
                                           Number( cols[ 6 ] ) + Number( cols[ 7 ] ) + Number( cols[ 8 ] );
                            let total = idle + non_idle;

                            return {
                                idle,
                                non_idle,
                                total
                            }
                        }

                        function calcula_uso_cpu( antes, despues )
                        {
                            let total = despues.numbers.total - antes.numbers.total;
                            let idle = despues.numbers.idle - antes.numbers.idle;

                            let uso = ( ( total - idle ) / total ) * 100;

                            return {
                                cpu : despues.key,
                                uso
                            }
                        }

                        function calcula_uso( cpus_antes, cpus_despues )
                        {
                            let ret = [];

                            for( const cpu of Object.keys( cpus_despues ) )
                            {
                                if( ! cpus_antes[ cpu ] ) { continue; }

                                let uso = calcula_uso_cpu( cpus_antes[ cpu ], cpus_despues[ cpu ] );

                                if( ! uso ) { continue; } 

                                ret.push( uso );
                            }

                            return ret;
                        }

                        let stdin_str = "";

                        for await ( const chunk of process.stdin )
                        {
                            stdin_str += chunk.toString();
                        }

                        let parts = stdin_str.toString().split( "---" );
                    
                        let info_cpus_antes = cpus_map( parts[ 0 ] );
                        let info_cpus_despues = cpus_map( parts[ 1 ] );

                        let uso = calcula_uso( info_cpus_antes, info_cpus_despues ); 

                        console.log( JSON.stringify( uso ) );
                    ]]>
                </arg>
            </args>
        </code>
        <code command="/usr/bin/bash" name="read-cpuinfo">
            <args>
                <arg>-c</arg>
                <arg>
                    <![CDATA[ 
                        grep "^cpu" /proc/stat
                        echo ---
                        sleep 1
                        grep "^cpu" /proc/stat
                    ]]>
                </arg>
            </args>
        </code>
        <style>
            {
                ".red" : {
                    "bg" : "#aa3333"
                },
                ".label-cpu" : {
                    "bg" : "#000011",
                    "fg" : "#bbbbff"
                },
                "border" : {
                    "bg" : "#000011",
                    "fg" : "#aaffaa"
                },
                "line, layout, body" : {
                    "bg" : "#000011"
                }
            }
        </style>
    </head>
    <body>
        <command exec="read-cpuinfo|parse-info" refresh-ms="10" output="json" dir="vertical" flex="center">
            <template>
                <layout dir="horizontal" flex="center" length="{{ ( ctx | length ) + 4 }}">
                    <border title="Cpuinfo" dir="vertical" max="111" flex="center" padding="1">
                        {% for uso in ctx %}
                        <layout flex="start" length="1" dir="horizontal">
                            <line length="6" align="right" class="label-cpu" padding="0,1,0,0">
                                {% if uso.cpu == "cpu" %}
                                    all:
                                {% else %}
                                    {{ uso.cpu | replace( "cpu", "" ) }}:
                                {% endif %}
                                
                            </line>
                            {% set porcentaje = ( uso.uso | round ) | int %}
                            {% set porcentaje_str = ( porcentaje | string ) + "%" %}
                            {% set porcentaje_str_len = porcentaje_str | length %}
                            {% for i in range( porcentaje ) %}
                                <line length="1" class="red">{% if porcentaje_str_len > i %}{{ porcentaje_str[ i ] }}{% else %} {% endif %}</line>
                            {% endfor %}
                            <line>{{ porcentaje_str[porcentaje:] }}</line>
                        </layout>
                        {% endfor %}
                    </border>
                </layout>
            </template>
        </command>
        
    </body>
</rtml>
